name: main

on: pull_request

jobs:
  list_files:
    runs-on: [ubuntu-latest,macos-latest]
    steps:
      - name: list files
        run: |
          ls -la /
  golangci_lint:
    runs-on: [ubuntu-latest,macos-latest]
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
