name: main

on: pull_request

jobs:
  golangci_lint:
    runs-on: macos-latest
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
